import { StyleSheet } from 'react-native';

import { GinitTheme } from '@/constants/ginit-theme';

export const supportScreenStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: GinitTheme.colors.bg },
  safe: { flex: 1, backgroundColor: GinitTheme.colors.bg },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 10,
    minHeight: 48,
  },
  backBtn: { padding: 4 },
  topTitle: { flex: 1, textAlign: 'center', fontSize: 17, fontWeight: '700', color: '#0f172a' },
  topBarSpacer: { width: 30 },
  /** 홈 모임 목록 `index.tsx` `styles.scroll`과 동일 */
  listContent: {
    paddingHorizontal: 20,
    paddingTop: 4,
    paddingBottom: 28,
    flexGrow: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 32,
  },
  card: {
    borderColor: GinitTheme.colors.border,
    marginBottom: GinitTheme.spacing.md,
  },
  label: {
    fontSize: 12,
    fontWeight: '600',
    color: GinitTheme.colors.textMuted,
    marginBottom: 6,
  },
  fieldHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  charCount: {
    fontSize: 12,
    fontWeight: '700',
    color: GinitTheme.colors.textMuted,
  },
  input: {
    minHeight: 48,
    borderRadius: 14,
    paddingHorizontal: GinitTheme.spacing.md,
    backgroundColor: GinitTheme.colors.bgAlt,
    borderWidth: 1,
    borderColor: GinitTheme.colors.border,
    color: GinitTheme.colors.text,
    fontSize: 16,
    fontWeight: '600',
  },
  bodyInput: {
    minHeight: 120,
    paddingTop: 12,
    textAlignVertical: 'top',
  },
  hintText: {
    fontSize: 13,
    fontWeight: '600',
    color: GinitTheme.colors.textMuted,
    lineHeight: 18,
    marginTop: 14,
    marginBottom: 10,
  },
  termsRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    paddingVertical: 8,
  },
  termsBox: {
    width: 26,
    height: 26,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    marginTop: 1,
  },
  termsBoxUnchecked: {
    borderColor: GinitTheme.colors.primary,
    backgroundColor: 'rgba(69, 39, 160, 0.06)',
  },
  termsBoxChecked: {
    borderColor: GinitTheme.colors.primary,
    backgroundColor: 'rgba(69, 39, 160, 0.12)',
  },
  termsCheckMark: { fontSize: 16, fontWeight: '600', color: GinitTheme.colors.primary },
  termsLabel: { flex: 1, fontSize: 14, fontWeight: '600', color: GinitTheme.colors.text, lineHeight: 20 },
  chipWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: GinitTheme.colors.border,
    backgroundColor: GinitTheme.colors.bgAlt,
  },
  chipSelected: {
    borderColor: GinitTheme.colors.primary,
    backgroundColor: 'rgba(69, 39, 160, 0.1)',
  },
  chipLabel: { fontSize: 14, fontWeight: '600', color: GinitTheme.colors.textSub },
  chipLabelSelected: { color: GinitTheme.colors.primary },
  footerRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: GinitTheme.spacing.lg,
  },
  footerBtn: { flex: 1 },
  emptyBox: { paddingVertical: 48, alignItems: 'center' },
  emptyText: { fontSize: 15, fontWeight: '600', color: GinitTheme.colors.textMuted },
  detailHero: {
    width: '100%',
    aspectRatio: 16 / 9,
    backgroundColor: GinitTheme.colors.bgAlt,
    marginBottom: 16,
  },
  detailTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: GinitTheme.colors.text,
    lineHeight: 24,
    letterSpacing: -0.25,
  },
  detailDate: {
    marginTop: 6,
    marginBottom: 14,
    fontSize: 12,
    fontWeight: '600',
    color: GinitTheme.colors.textMuted,
    letterSpacing: -0.12,
  },
  detailDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: GinitTheme.colors.border,
    marginBottom: 14,
  },
  detailBody: {
    fontSize: 15,
    fontWeight: '500',
    color: GinitTheme.colors.textSub,
    lineHeight: 22,
    letterSpacing: -0.15,
  },
  centerLoad: { paddingVertical: 40, alignItems: 'center' },
});
