declare namespace NodeJS {
  interface ProcessEnv {
    EXPO_PUBLIC_SUPABASE_URL?: string;
    EXPO_PUBLIC_SUPABASE_ANON_KEY?: string;
    EXPO_PUBLIC_NAVER_MAP_CLIENT_ID?: string;
    EXPO_PUBLIC_NAVER_MAPS_API_ORIGIN?: string;
    EXPO_PUBLIC_NAVER_MAPS_GEOCODE_PATH?: string;
    EXPO_PUBLIC_NAVER_SEARCH_CLIENT_ID?: string;
    EXPO_PUBLIC_NAVER_SEARCH_CLIENT_SECRET?: string;
    EXPO_PUBLIC_NAVER_LOCAL_CLIENT_ID?: string;
    EXPO_PUBLIC_NAVER_LOCAL_CLIENT_SECRET?: string;
    EXPO_PUBLIC_NAVER_LOCAL_SEARCH_CORS_PROXY?: string;
    EXPO_PUBLIC_NAVER_LOCAL_SEARCH_API_BASE?: string;
    EXPO_PUBLIC_FIREBASE_API_KEY?: string;
    EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN?: string;
    EXPO_PUBLIC_FIREBASE_PROJECT_ID?: string;
    EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET?: string;
    EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID?: string;
    EXPO_PUBLIC_FIREBASE_APP_ID?: string;
    WEB_CLIENT_ID?: string;
    EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID?: string;
  }
}
