/**
 * Android Direct Share (Sharing Shortcuts + ACTION_SEND receive)
 * - Injects ShareReceiver activity + shortcuts.xml + native bridge module.
 *
 * NOTE: android/ is generated by Expo prebuild, so this plugin patches generated files.
 */
const { withAndroidManifest, withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const PREFS_NAME = 'ginit_direct_share_prefs';

function mkdirp(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function writeFileIfChanged(filePath, contents) {
  const prev = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf8') : '';
  if (prev === contents) return;
  mkdirp(path.dirname(filePath));
  fs.writeFileSync(filePath, contents);
}

function ensureArray(v) {
  if (!v) return [];
  return Array.isArray(v) ? v : [v];
}

function addOrReplaceActivity(app, activity) {
  const list = ensureArray(app.activity);
  const name = activity?.$?.['android:name'];
  if (!name) return;
  const next = [];
  let replaced = false;
  for (const a of list) {
    if (a?.$?.['android:name'] === name) {
      next.push(activity);
      replaced = true;
    } else {
      next.push(a);
    }
  }
  if (!replaced) next.push(activity);
  app.activity = next;
}

function addOrReplaceMeta(app, item) {
  const list = ensureArray(app['meta-data']);
  const name = item?.$?.['android:name'];
  if (!name) return;
  const next = [];
  let replaced = false;
  for (const m of list) {
    if (m?.$?.['android:name'] === name) {
      next.push(item);
      replaced = true;
    } else {
      next.push(m);
    }
  }
  if (!replaced) next.push(item);
  app['meta-data'] = next;
}

function withDirectShareManifest(config) {
  return withAndroidManifest(config, (mod) => {
    const manifest = mod.modResults?.manifest;
    if (!manifest) return mod;
    manifest.$ = manifest.$ ?? {};
    if (!manifest.$['xmlns:tools']) {
      manifest.$['xmlns:tools'] = 'http://schemas.android.com/tools';
    }

    const app = manifest.application?.[0];
    if (!app) return mod;

    // Shortcuts xml
    addOrReplaceMeta(app, {
      $: {
        'android:name': 'android.app.shortcuts',
        'android:resource': '@xml/shortcuts',
        'tools:replace': 'android:resource',
      },
    });

    // Receiver activity for ACTION_SEND + share targets
    addOrReplaceActivity(app, {
      $: {
        'android:name': 'com.ginit.app.directshare.DirectShareReceiverActivity',
        'android:exported': 'true',
        'android:launchMode': 'singleTask',
        'android:excludeFromRecents': 'true',
        'android:taskAffinity': '',
      },
      'intent-filter': [
        {
          action: [{ $: { 'android:name': 'android.intent.action.SEND' } }],
          category: [{ $: { 'android:name': 'android.intent.category.DEFAULT' } }],
          // Chrome / NaverMap / etc: often text/plain
          data: [{ $: { 'android:mimeType': 'text/plain' } }],
        },
        {
          action: [{ $: { 'android:name': 'android.intent.action.SEND' } }],
          category: [{ $: { 'android:name': 'android.intent.category.DEFAULT' } }],
          // Some apps share links as text/html or other text/*
          data: [{ $: { 'android:mimeType': 'text/*' } }],
        },
        {
          action: [{ $: { 'android:name': 'android.intent.action.SEND' } }],
          category: [{ $: { 'android:name': 'android.intent.category.DEFAULT' } }],
          data: [{ $: { 'android:mimeType': 'image/*' } }],
        },
        {
          // Instagram / Gallery multi-select can use SEND_MULTIPLE
          action: [{ $: { 'android:name': 'android.intent.action.SEND_MULTIPLE' } }],
          category: [{ $: { 'android:name': 'android.intent.category.DEFAULT' } }],
          data: [{ $: { 'android:mimeType': 'image/*' } }],
        },
      ],
    });

    return mod;
  });
}

function withDirectShareNativeFiles(config) {
  return withDangerousMod(config, [
    'android',
    async (cfg) => {
      const projectRoot = cfg.modRequest.projectRoot;

      // Patch android/settings.gradle to avoid fragile providers.exec node resolution in some environments.
      // (We still keep Expo's structure, just make react-native gradle plugin path deterministic.)
      try {
        const settingsPath = path.join(projectRoot, 'android/settings.gradle');
        if (fs.existsSync(settingsPath)) {
          let s = fs.readFileSync(settingsPath, 'utf8');
          const hardcoded = `  def reactNativeGradlePlugin = new File(rootDir, "../node_modules/@react-native/gradle-plugin").absolutePath
  includeBuild(reactNativeGradlePlugin)
`;
          // Replace the whole block that computes reactNativeGradlePlugin via providers.exec.
          s = s.replace(
            /(\n\s*)def\s+reactNativeGradlePlugin\s*=\s*new\s+File\([\s\S]*?\)\.getParentFile\(\)\.absolutePath\s*\n\s*includeBuild\(reactNativeGradlePlugin\)\s*\n/m,
            `\n${hardcoded}`,
          );
          fs.writeFileSync(settingsPath, s);
        }
      } catch {
        // best-effort
      }

      // 1) res/xml/shortcuts.xml
      const shortcutsXmlPath = path.join(projectRoot, 'android/app/src/main/res/xml/shortcuts.xml');
      const shortcutsXml = `<?xml version="1.0" encoding="utf-8"?>
<shortcuts xmlns:android="http://schemas.android.com/apk/res/android">
  <!-- Share target definition for Android Direct Share. Dynamic shortcuts are published at runtime. -->
  <share-target android:targetClass="com.ginit.app.directshare.DirectShareReceiverActivity">
    <data android:mimeType="text/plain" />
    <data android:mimeType="text/*" />
    <data android:mimeType="image/*" />
    <category android:name="android.intent.category.DEFAULT" />
  </share-target>
</shortcuts>
`;
      writeFileIfChanged(shortcutsXmlPath, shortcutsXml);

      // 2) Kotlin sources under android/app/src/main/java/com/ginit/app/directshare
      const pkgDir = path.join(projectRoot, 'android/app/src/main/java/com/ginit/app/directshare');
      mkdirp(pkgDir);

      const receiverPath = path.join(pkgDir, 'DirectShareReceiverActivity.kt');
      const receiverKt = `package com.ginit.app.directshare

import android.content.Context
import android.content.Intent
import android.net.Uri
import android.os.Bundle
import androidx.appcompat.app.AppCompatActivity
import java.io.File
import java.io.FileOutputStream

class DirectShareReceiverActivity : AppCompatActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    try {
      handleIncomingIntent(intent)
    } catch (_: Throwable) {
      // ignore
    } finally {
      finish()
    }
  }

  override fun onNewIntent(intent: Intent) {
    super.onNewIntent(intent)
    try {
      handleIncomingIntent(intent)
    } catch (_: Throwable) {
      // ignore
    } finally {
      finish()
    }
  }

  private fun safeCopyUriToCache(uri: Uri): String? {
    return try {
      val resolver = applicationContext.contentResolver
      val input = resolver.openInputStream(uri) ?: return null
      input.use { ins ->
        val outFile = File(cacheDir, "direct_share_\${System.currentTimeMillis()}.jpg")
        FileOutputStream(outFile).use { fos ->
          val buf = ByteArray(64 * 1024)
          while (true) {
            val n = ins.read(buf)
            if (n <= 0) break
            fos.write(buf, 0, n)
          }
          fos.flush()
        }
        Uri.fromFile(outFile).toString()
      }
    } catch (_: Throwable) {
      null
    }
  }

  private fun handleIncomingIntent(i: Intent) {
    val action = i.action ?: ""
    if (action != Intent.ACTION_SEND && action != Intent.ACTION_SEND_MULTIPLE) return

    val prefs = getSharedPreferences("${PREFS_NAME}", Context.MODE_PRIVATE)
    val edit = prefs.edit()

    val text = i.getStringExtra(Intent.EXTRA_TEXT)?.trim()
    val stream = i.getParcelableExtra<Uri>(Intent.EXTRA_STREAM)
    val streams = i.getParcelableArrayListExtra<Uri>(Intent.EXTRA_STREAM)

    val targetType = i.getStringExtra("targetType")?.trim()
    val targetId = i.getStringExtra("targetId")?.trim()

    if (!text.isNullOrEmpty()) edit.putString("text", text) else edit.remove("text")
    val firstStream = stream ?: (if (streams != null && streams.size > 0) streams[0] else null)
    if (firstStream != null) {
      val copied = safeCopyUriToCache(firstStream)
      if (!copied.isNullOrEmpty()) edit.putString("imageUri", copied) else edit.putString("imageUri", firstStream.toString())
    } else {
      edit.remove("imageUri")
    }
    if (!targetType.isNullOrEmpty()) edit.putString("targetType", targetType) else edit.remove("targetType")
    if (!targetId.isNullOrEmpty()) edit.putString("targetId", targetId) else edit.remove("targetId")
    edit.putLong("ts", System.currentTimeMillis())
    edit.apply()

    // IMPORTANT: use triple-slash so Expo Linking treats this as a pathname (/direct-share),
    // not a host (direct-share). Otherwise it can fall back to the default route.
    val route = if (!targetType.isNullOrEmpty() && !targetId.isNullOrEmpty()) {
      "ginitapp:///direct-share?targetType=" + Uri.encode(targetType) + "&targetId=" + Uri.encode(targetId)
    } else {
      "ginitapp:///direct-share"
    }
    val open = Intent(Intent.ACTION_VIEW, Uri.parse(route))
    open.setPackage(packageName)
    open.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TOP)
    startActivity(open)
  }
}
`;
      writeFileIfChanged(receiverPath, receiverKt);

      const modulePath = path.join(pkgDir, 'GinitDirectShareModule.kt');
      const moduleKt = `package com.ginit.app.directshare

import android.content.Context
import android.content.Intent
import androidx.core.content.pm.ShortcutInfoCompat
import androidx.core.content.pm.ShortcutManagerCompat
import androidx.core.graphics.drawable.IconCompat
import com.facebook.react.bridge.Arguments
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReactContextBaseJavaModule
import com.facebook.react.bridge.ReactMethod
import com.facebook.react.bridge.ReadableArray
import com.facebook.react.bridge.ReadableMap
import com.facebook.react.bridge.ReadableType

class GinitDirectShareModule(reactContext: ReactApplicationContext) : ReactContextBaseJavaModule(reactContext) {
  override fun getName(): String = "GinitDirectShare"

  @ReactMethod
  fun consumePendingShare(promise: Promise) {
    try {
      val prefs = reactApplicationContext.getSharedPreferences("${PREFS_NAME}", Context.MODE_PRIVATE)
      val text = prefs.getString("text", null)
      val imageUri = prefs.getString("imageUri", null)
      val targetType = prefs.getString("targetType", null)
      val targetId = prefs.getString("targetId", null)
      prefs.edit()
        .remove("text")
        .remove("imageUri")
        .remove("targetType")
        .remove("targetId")
        .remove("ts")
        .apply()
      if (text == null && imageUri == null && targetType == null && targetId == null) {
        promise.resolve(null)
        return
      }
      val out = Arguments.createMap()
      if (text != null) out.putString("text", text)
      if (imageUri != null) out.putString("imageUri", imageUri)
      if (targetType != null) out.putString("targetType", targetType)
      if (targetId != null) out.putString("targetId", targetId)
      promise.resolve(out)
    } catch (t: Throwable) {
      promise.resolve(null)
    }
  }

  @ReactMethod
  fun setShareShortcuts(items: ReadableArray, promise: Promise) {
    try {
      val ctx = reactApplicationContext
      val list = ArrayList<ShortcutInfoCompat>()
      for (i in 0 until items.size()) {
        val item = items.getMap(i) ?: continue
        val id = item.getString("id")?.trim() ?: continue
        val title = item.getString("title")?.trim() ?: continue
        val subtitle = item.getString("subtitle")?.trim()
        val targetType = item.getString("targetType")?.trim()
        val targetId = item.getString("targetId")?.trim()

        val intent = Intent(Intent.ACTION_SEND)
        intent.type = "text/plain"
        intent.setClassName(ctx.packageName, "com.ginit.app.directshare.DirectShareReceiverActivity")
        if (!targetType.isNullOrEmpty()) intent.putExtra("targetType", targetType)
        if (!targetId.isNullOrEmpty()) intent.putExtra("targetId", targetId)

        val b = ShortcutInfoCompat.Builder(ctx, id)
          .setShortLabel(title)
          .setIntent(intent)
          .setIcon(IconCompat.createWithResource(ctx, ctx.applicationInfo.icon))
        if (!subtitle.isNullOrEmpty()) b.setLongLabel(subtitle)
        list.add(b.build())
      }
      ShortcutManagerCompat.removeAllDynamicShortcuts(ctx)
      ShortcutManagerCompat.addDynamicShortcuts(ctx, list)
      promise.resolve(null)
    } catch (t: Throwable) {
      promise.resolve(null)
    }
  }
}
`;
      writeFileIfChanged(modulePath, moduleKt);

      const pkgPath = path.join(pkgDir, 'GinitDirectSharePackage.kt');
      const pkgKt = `package com.ginit.app.directshare

import com.facebook.react.ReactPackage
import com.facebook.react.bridge.NativeModule
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.uimanager.ViewManager

class GinitDirectSharePackage : ReactPackage {
  override fun createNativeModules(reactContext: ReactApplicationContext): List<NativeModule> {
    return listOf(GinitDirectShareModule(reactContext))
  }

  override fun createViewManagers(reactContext: ReactApplicationContext): List<ViewManager<*, *>> {
    return emptyList()
  }
}
`;
      writeFileIfChanged(pkgPath, pkgKt);

      // 3) Register package in MainApplication (Kotlin/Java) via string insertion.
      const mainAppGlobRoot = path.join(projectRoot, 'android/app/src/main/java');
      // best-effort: search typical generated file locations without glob dependency.
      // Expo generated MainApplication is usually at android/app/src/main/java/**/MainApplication.(kt|java).
      // We'll do a shallow recursive search up to a few levels.
      const candidates = [];
      function walk(dir, depth) {
        if (depth > 6) return;
        let entries = [];
        try {
          entries = fs.readdirSync(dir, { withFileTypes: true });
        } catch {
          return;
        }
        for (const e of entries) {
          const p = path.join(dir, e.name);
          if (e.isDirectory()) walk(p, depth + 1);
          else if (e.isFile() && (e.name === 'MainApplication.kt' || e.name === 'MainApplication.java')) candidates.push(p);
        }
      }
      walk(mainAppGlobRoot, 0);
      const mainAppPath = candidates[0];
      if (mainAppPath && fs.existsSync(mainAppPath)) {
        let c = fs.readFileSync(mainAppPath, 'utf8');
        const marker = 'com.ginit.app.directshare.GinitDirectSharePackage';
        if (!c.includes(marker)) {
          const isKt = mainAppPath.endsWith('.kt');
          if (isKt) {
            // import
            const pkgMatch = c.match(/^package\s+[^\n]+\n/m);
            const insertAt = pkgMatch ? pkgMatch.index + pkgMatch[0].length : 0;
            if (!c.includes('import com.ginit.app.directshare.GinitDirectSharePackage')) {
              c = c.slice(0, insertAt) + 'import com.ginit.app.directshare.GinitDirectSharePackage\n' + c.slice(insertAt);
            }
            // add to packages list: support both "val packages = PackageList(this).packages"
            // and "PackageList(this).packages.apply { ... }" (Expo prebuild Kotlin template).
            const reVal = /val\s+packages\s*=\s*PackageList\(this\)\.packages\s*\n/;
            const mv = c.match(reVal);
            if (mv && mv.index != null) {
              const end = mv.index + mv[0].length;
              c = c.slice(0, end) + '    packages.add(GinitDirectSharePackage())\n' + c.slice(end);
            } else {
              const reApply = /PackageList\(this\)\.packages\.apply\s*\{\s*\n/;
              const ma = c.match(reApply);
              if (ma && ma.index != null) {
                const end = ma.index + ma[0].length;
                c = c.slice(0, end) + '              add(GinitDirectSharePackage())\n' + c.slice(end);
              }
            }
          } else {
            const pkgMatch = c.match(/^package\s+[^;]+;\s*\n/m);
            const insertAt = pkgMatch ? pkgMatch.index + pkgMatch[0].length : 0;
            if (!c.includes('import com.ginit.app.directshare.GinitDirectSharePackage;')) {
              c = c.slice(0, insertAt) + 'import com.ginit.app.directshare.GinitDirectSharePackage;\n' + c.slice(insertAt);
            }
            const re = /List<ReactPackage>\s+packages\s*=\s*new PackageList\(this\)\.getPackages\(\);\s*\n/;
            const m = c.match(re);
            if (m && m.index != null) {
              const end = m.index + m[0].length;
              c = c.slice(0, end) + '    packages.add(new GinitDirectSharePackage());\n' + c.slice(end);
            }
          }
          fs.writeFileSync(mainAppPath, c);
        }
      }

      return cfg;
    },
  ]);
}

/** @type {import('@expo/config-plugins').ConfigPlugin} */
module.exports = function withAndroidDirectShare(config) {
  const c1 = withDirectShareManifest(config);
  const c2 = withDirectShareNativeFiles(c1);
  return c2;
};

