import { StyleSheet } from 'react-native';

import { GinitTheme } from '@/constants/ginit-theme';

/**
 * 모임/1:1 공용 채팅 본문(리스트·말풍선·composer·이미지 뷰어) 스타일.
 * `app/meeting-chat/[meetingId]/index.tsx`와 동일 수치 유지.
 */
export const meetingChatBodyStyles = StyleSheet.create({
  chatMainColumn: {
    flex: 1,
    minHeight: 0,
    position: 'relative',
  },
  composerDock: {
    width: '100%',
    flexShrink: 0,
    backgroundColor: '#fff',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: 'rgba(15, 23, 42, 0.08)',
  },
  bottomSearchNavigatorWrap: {
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 6,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: 'rgba(15, 23, 42, 0.08)',
  },
  /** `KeyboardStickyView`: 리스트와 겹치지 않게 하단 고정(레이아웃 플로우 밖). */
  composerStickyWrap: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 20,
  },
  listWrap: {
    flex: 1,
    position: 'relative',
    backgroundColor: '#ECEFF1',
  },
  searchJumpLoadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.55)',
    zIndex: 12,
    gap: 10,
  },
  searchJumpLoadingText: {
    fontSize: 14,
    fontWeight: '700',
    color: GinitTheme.colors.textSub,
  },
  plusListDismissLayer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 4,
    backgroundColor: 'transparent',
  },
  plusFanFloating: {
    position: 'absolute',
    left: 0,
    right: 0,
    zIndex: 7,
  },
  dateChipRow: {
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 2,
  },
  dateChip: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.55)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.22)',
  },
  dateChipText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#475569',
  },
  chatErrorBanner: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: 'rgba(220, 38, 38, 0.12)',
  },
  chatErrorText: { fontSize: 12, color: '#991b1b' },
  chatListFooterSpinner: {
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  listContent: {
    paddingHorizontal: 12,
    paddingTop: 4,
    paddingBottom: 16,
    flexGrow: 1,
  },
  emptyChat: {
    textAlign: 'center',
    marginTop: 40,
    fontSize: 14,
    color: '#94a3b8',
  },
  jumpFab: {
    position: 'absolute',
    right: 16,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.95)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(103, 58, 183, 0.34)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 3,
    zIndex: 8,
  },
  systemRow: {
    alignItems: 'center',
    marginVertical: 8,
  },
  systemText: {
    fontSize: 12,
    color: '#94a3b8',
  },
  rowMine: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
    gap: 6,
    marginBottom: 10,
  },
  bubbleMineWrap: {
    maxWidth: '78%',
  },
  bubbleMine: {
    backgroundColor: 'rgba(103, 58, 183, 0.22)',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 16,
    borderTopRightRadius: 4,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(103, 58, 183, 0.30)',
    overflow: 'hidden',
  },
  bubbleMineMedia: {
    paddingHorizontal: 6,
    paddingVertical: 6,
    maxWidth: '100%',
  },
  bubbleMineText: {
    fontSize: 15,
    color: '#0f172a',
    lineHeight: 20,
  },
  chatImage: {
    width: 220,
    maxWidth: '100%',
    aspectRatio: 1,
    borderRadius: 12,
    backgroundColor: '#e2e8f0',
    alignSelf: 'flex-start',
  },
  chatImageAlbumGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: 220,
    maxWidth: '100%',
    gap: 2,
    alignSelf: 'flex-start',
  },
  chatImageAlbumCellWrap: {
    width: 109,
    height: 109,
    borderRadius: 10,
    overflow: 'hidden',
    backgroundColor: '#e2e8f0',
  },
  chatImageAlbumCell: {
    width: '100%',
    height: '100%',
  },
  /** 지닛 묶음 사진(말풍선 없음). 둥근 모서리 밖으로 이미지가 나가지 않도록 외곽에서 클립 */
  ginitClusterOuter: {
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: '#e2e8f0',
    maxWidth: '100%',
  },
  ginitRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 0,
    columnGap: 0,
    rowGap: 0,
  },
  ginitCol: {
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: 0,
    columnGap: 0,
    rowGap: 0,
  },
  ginitGrid4: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignContent: 'flex-start',
    gap: 0,
    columnGap: 0,
    rowGap: 0,
  },
  ginitCellInner: {
    overflow: 'hidden',
    backgroundColor: '#e2e8f0',
  },
  ginitCellImage: {
    width: '100%',
    height: '100%',
  },
  ginitSingleCell: {
    width: '100%',
    minHeight: 160,
    maxHeight: 320,
  },
  ginitMoreOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15, 23, 42, 0.48)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  ginitMoreText: {
    fontSize: 22,
    fontWeight: '800',
    color: '#fff',
  },
  ginitPlainMineWrap: {
    maxWidth: '78%',
    alignItems: 'flex-end',
  },
  ginitPlainOtherOuter: {
    maxWidth: '78%',
    alignSelf: 'flex-start',
  },
  viewerPagerList: {
    flexGrow: 1,
  },
  viewerPagerPage: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'stretch',
  },
  pendingImageStrip: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    paddingHorizontal: 10,
    paddingTop: 6,
    paddingBottom: 2,
  },
  pendingImageThumbWrap: {
    position: 'relative',
  },
  pendingImageThumb: {
    width: 56,
    height: 56,
    borderRadius: 10,
    backgroundColor: '#e2e8f0',
  },
  pendingImageRemove: {
    position: 'absolute',
    top: -4,
    right: -4,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: 'rgba(15, 23, 42, 0.75)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  imageCaptionMine: {
    marginTop: 6,
    paddingHorizontal: 6,
    fontSize: 14,
    color: '#0f172a',
    lineHeight: 19,
  },
  timeMineCol: {
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
  },
  unreadBubbleCount: {
    fontSize: 11,
    fontWeight: '600',
    color: '#000000',
    marginBottom: 2,
  },
  timeMine: {
    fontSize: 11,
    color: '#94a3b8',
    marginBottom: 2,
  },
  rowOther: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    marginBottom: 10,
  },
  avatarCol: {
    width: 40,
  },
  avatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#e2e8f0',
  },
  avatarWithdrawn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#e2e8f0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarFallback: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(0, 82, 204, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarFallbackText: {
    fontSize: 15,
    fontWeight: '600',
    color: GinitTheme.colors.primary,
  },
  avatarSpacer: {
    width: 36,
    height: 36,
  },
  otherBlock: {
    flex: 1,
    minWidth: 0,
  },
  nameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 4,
  },
  nickname: {
    fontSize: 13,
    fontWeight: '600',
    color: '#0f172a',
    maxWidth: '85%',
  },
  crown: { marginTop: -1 },
  bubbleOtherWrap: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 6,
  },
  bubbleOtherOuter: {
    maxWidth: '78%',
    position: 'relative',
  },
  bubbleOther: {
    backgroundColor: 'rgba(255,255,255,0.58)',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 16,
    borderTopLeftRadius: 4,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(15, 23, 42, 0.08)',
    overflow: 'hidden',
  },
  aiNeonOutline: {
    position: 'absolute',
    top: -1,
    left: -1,
    right: -1,
    bottom: -1,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 138, 0, 0.85)',
    shadowColor: '#FF8A00',
    shadowOpacity: 0.55,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 0 },
  },
  bubbleOtherMedia: {
    paddingHorizontal: 6,
    paddingVertical: 6,
    maxWidth: '100%',
  },
  bubbleOtherText: {
    fontSize: 15,
    color: '#0f172a',
    lineHeight: 20,
  },
  imageCaptionOther: {
    marginTop: 6,
    paddingHorizontal: 6,
    fontSize: 14,
    color: '#0f172a',
    lineHeight: 19,
  },
  timeOther: {
    fontSize: 11,
    color: '#94a3b8',
    marginBottom: 2,
  },
  replyQuoteMine: {
    marginBottom: 8,
    paddingLeft: 0,
    borderLeftWidth: 0,
    borderLeftColor: 'transparent',
  },
  replyQuoteOther: {
    marginBottom: 8,
    paddingLeft: 0,
    borderLeftWidth: 0,
    borderLeftColor: 'transparent',
  },
  replyQuoteLabelMine: { fontSize: 11, fontWeight: '600', color: '#0f172a' },
  replyQuoteLabelOther: { fontSize: 11, fontWeight: '600', color: '#0f172a' },
  replyQuoteTextMine: { marginTop: 2, fontSize: 12, color: '#0f172a' },
  replyQuoteTextOther: { marginTop: 2, fontSize: 12, color: '#0f172a' },
  replyQuoteTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    alignSelf: 'flex-start',
    maxWidth: '100%',
  },
  replyQuoteTextCol: { flexShrink: 1, minWidth: 0 },
  replyQuoteThumb: {
    width: 34,
    height: 34,
    borderRadius: 8,
    backgroundColor: '#e2e8f0',
  },
  replyQuotePressable: {
    alignSelf: 'flex-start',
    maxWidth: '100%',
  },
  replyDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: 'rgba(15, 23, 42, 0.16)',
    marginBottom: 8,
  },
  replyPreviewRow: {
    paddingHorizontal: 10,
    paddingTop: 10,
  },
  replyPreviewCard: {
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: 'rgba(255,255,255,0.55)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.22)',
    overflow: 'hidden',
  },
  replyPreviewIconWrap: {
    width: 44,
    height: 44,
    marginBottom: 2,
    marginLeft: -12,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    borderWidth: 0,
    borderColor: 'transparent',
  },
  replyPreviewTextCol: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'column',
    gap: 2,
  },
  replyPreviewTitle: { fontSize: 13, fontWeight: '600', color: '#0f172a' },
  replyPreviewBody: { fontSize: 12, fontWeight: '600', color: '#0f172a' },
  replyPreviewThumbOuter: {
    width: 28,
    height: 28,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: '#e2e8f0',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(15, 23, 42, 0.12)',
  },
  replyPreviewThumb: { width: '100%', height: '100%' },
  composerCluster: {
    width: '100%',
  },
  plusFanInner: {
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 4,
  },
  plusQuickMeasureHost: {
    position: 'absolute',
    left: -8000,
    top: 0,
    opacity: 0,
  },
  plusFanLabelMorph: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
    letterSpacing: -0.2,
    flexShrink: 1,
  },
  plusQuickIconLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  pressed: {
    opacity: 0.85,
  },
  viewerRoot: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.92)',
    justifyContent: 'center',
    alignItems: 'stretch',
  },
  viewerSheet: {
    flex: 1,
    paddingBottom: 12,
  },
  viewerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingBottom: 10,
  },
  viewerMetaCol: {
    flex: 1,
    marginLeft: 6,
    marginRight: 8,
    justifyContent: 'center',
    minWidth: 0,
  },
  viewerMetaName: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
  },
  viewerMetaTime: {
    marginTop: 2,
    color: 'rgba(255,255,255,0.72)',
    fontSize: 12,
    fontWeight: '500',
  },
  viewerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  viewerImageWrap: {
    flex: 1,
    width: '100%',
    minHeight: 0,
    backgroundColor: 'transparent',
  },
  composer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 8,
    paddingHorizontal: 10,
    paddingTop: 8,
    paddingBottom: 8,
  },
  plusBtn: {
    width: 30,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 2,
  },
  plusBtnIconSlot: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  plusBtnIconLayer: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
  },
  inputShell: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f1f5f9',
    borderRadius: 20,
    paddingHorizontal: 14,
    minHeight: 44,
    maxHeight: 120,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(15, 23, 42, 0.08)',
  },
  input: {
    flex: 1,
    fontSize: 15,
    color: '#0f172a',
    paddingVertical: 10,
    maxHeight: 100,
  },
  sendBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: GinitTheme.colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 2,
  },
  sendBtnDisabled: {
    opacity: 0.5,
  },
});
