import { Platform, StyleSheet } from 'react-native';

import { GinitTheme } from '@/constants/ginit-theme';

/** 일정·장소 투표 후보 폼(`VoteCandidatesForm`) 전용 스타일 — `details.tsx`와 동일 토큰 복제(픽셀 무변). */
export const voteCandidatesFormStyles = StyleSheet.create({
  scrollContent: {
    paddingTop: 6,
    paddingBottom: 28,
  },
  sectionHeader: {
    marginBottom: 6,
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: '600',
    color: GinitTheme.colors.text,
    letterSpacing: -0.35,
  },
  sectionHint: {
    fontSize: 13,
    fontWeight: '600',
    color: GinitTheme.colors.textMuted,
    lineHeight: 19,
    marginBottom: 10,
  },
  /** 자연어 일정 입력 — 리스트 상단 */
  nlpSection: {
    marginBottom: 6,
  },
  aiQuickInitLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: GinitTheme.colors.textMuted,
    marginBottom: 8,
    letterSpacing: 0.2,
  },
  aiQuickInitBorder: {
    borderRadius: 16,
    padding: 2,
    marginBottom: 8,
  },
  aiQuickInitInner: {
    borderRadius: 14,
    backgroundColor: GinitTheme.colors.surface,
    borderWidth: 1,
    borderColor: GinitTheme.colors.border,
    paddingHorizontal: 12,
    paddingVertical: 10,
    minHeight: 20,
  },
  aiQuickInitInput: {
    minHeight: 20,
    fontSize: 16,
    fontWeight: '700',
    color: GinitTheme.colors.text,
    lineHeight: 22,
    padding: 0,
    margin: 0,
  },
  voiceInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  voiceInput: {
    flex: 1,
  },
  voiceBtn: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(31, 42, 68, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(31, 42, 68, 0.45)',
  },
  voiceBtnPressed: {
    opacity: 0.85,
    transform: [{ scale: 0.98 }],
  },
  voiceWaveWrap: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'center',
    gap: 3,
    height: 18,
  },
  voiceWaveBar: {
    width: 3,
    height: 18,
    borderRadius: 2,
    opacity: 0.95,
  },
  aiPreviewRow: {
    marginTop: 2,
    marginBottom: 8,
    gap: 8,
  },
  aiPreviewHint: {
    fontSize: 12,
    fontWeight: '600',
    color: GinitTheme.colors.textMuted,
  },
  aiPreviewScroll: {
    gap: 8,
    paddingBottom: 2,
    paddingRight: 0,
  },
  /** `PublicMeetingDetailsCard` 모집 연령대 칩과 동일 스펙 */
  aiPreviewScheduleChip: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: GinitTheme.colors.border,
    backgroundColor: Platform.OS === 'android' ? '#FFFFFF' : 'rgba(255, 255, 255, 0.55)',
    paddingVertical: 9,
    paddingHorizontal: 12,
    overflow: 'hidden',
    justifyContent: 'center',
  },
  aiPreviewScheduleChipCarousel: {
    width: 220,
    flexShrink: 0,
  },
  aiPreviewScheduleChipFull: {
    width: '100%',
    alignSelf: 'stretch',
  },
  aiPreviewScheduleChipLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: GinitTheme.colors.text,
  },
  aiPreviewScheduleChipHint: {
    fontSize: 13,
    fontWeight: '600',
    color: GinitTheme.colors.textMuted,
  },
  aiPreviewScheduleChipPlaceholder: {
    width: '100%',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: GinitTheme.colors.border,
    backgroundColor: Platform.OS === 'android' ? '#FFFFFF' : 'rgba(255, 255, 255, 0.55)',
    paddingVertical: 9,
    paddingHorizontal: 12,
    overflow: 'hidden',
    justifyContent: 'center',
  },
  aiPreviewScheduleChipPressed: {
    opacity: 0.82,
    transform: [{ scale: 0.99 }],
  },
  aiPreviewPill: {
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: GinitTheme.colors.primarySoft,
    borderWidth: 1,
    borderColor: GinitTheme.colors.border,
    marginBottom: 10,
  },
  aiPreviewPillText: {
    fontSize: 11,
    fontWeight: '600',
    color: GinitTheme.colors.primary,
  },
  aiPreviewClickableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  aiPreviewPlusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: GinitTheme.colors.primarySoft,
    borderWidth: 1,
    borderColor: GinitTheme.colors.border,
  },
  aiPreviewPlusText: {
    fontSize: 12,
    fontWeight: '600',
    color: GinitTheme.colors.primary,
    letterSpacing: -0.1,
  },
  aiQuickInitCta: {
    borderRadius: 16,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    borderWidth: 1,
    borderColor: GinitTheme.fixedGlassCard.border,
    ...GinitTheme.shadow.card,
  },
  aiQuickInitCtaBg: {
    ...StyleSheet.absoluteFillObject,
  },
  aiQuickInitCtaLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: GinitTheme.colors.text,
    letterSpacing: -0.2,
  },
  aiQuickInitCtaPressed: {
    opacity: 0.92,
    transform: [{ scale: 0.99 }],
  },
  nlpChip: {
    alignSelf: 'flex-start',
    marginTop: 10,
    marginBottom: 6,
    paddingVertical: 9,
    paddingHorizontal: 14,
    borderRadius: 999,
    backgroundColor: 'rgba(31, 42, 68, 0.22)',
    borderWidth: 1,
    borderColor: 'rgba(31, 42, 68, 0.45)',
  },
  nlpChipPressed: {
    opacity: 0.88,
    transform: [{ scale: 0.98 }],
  },
  nlpChipText: {
    fontSize: 13,
    fontWeight: '600',
    color: GinitTheme.colors.textOnDark,
    letterSpacing: -0.2,
  },
  sectionGap: {
    marginTop: 18,
  },
  /** 글래스 카드: shadow wrapper + clip inner (Android elevation 안전) */
  glassCardWrap: {
    marginBottom: 12,
    borderRadius: 24,
    backgroundColor: 'rgba(31, 42, 68, 0.04)',
    shadowColor: GinitTheme.shadow.card.shadowColor,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 1,
    shadowRadius: 24,
    elevation: 14,
  },
  flatWrapNoShadow: {
    shadowColor: 'transparent',
    shadowOpacity: 0,
    shadowRadius: 0,
    shadowOffset: { width: 0, height: 0 },
    elevation: 0,
  },
  glassCardInner: {
    borderRadius: 24,
    padding: 14,
    backgroundColor: 'rgba(31, 42, 68, 0.04)',
    borderWidth: 1.5,
    borderColor: 'rgba(31, 42, 68, 0.18)',
    overflow: 'hidden',
    position: 'relative',
  },
  /** 장소 후보 카드 전용(컴팩트) — 너무 큰 박스 방지 */
  placeCardOuter: {
    padding: 12,
  },
  deleteIconBtn: {
    position: 'absolute',
    top: 0,
    right: 0,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: GinitTheme.glass.overlayDark,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
  },
  cardFieldTitleNoDeleteOffset: {
    paddingRight: 0,
  },
  deleteIconText: {
    color: GinitTheme.colors.textOnDark,
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 16,
  },
  /** 카드 안 제목 (일정 후보 1 등) */
  cardFieldTitle: {
    color: GinitTheme.colors.text,
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 8,
    paddingRight: 40,
  },
  row2: {
    flexDirection: 'row',
    gap: 8,
  },
  /** 음각 필드 래퍼 */
  fieldRecess: {
    backgroundColor: 'rgba(31, 42, 68, 0.04)', // 네이비 틴트
    borderColor: GinitTheme.colors.borderStrong,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  placeFieldRecess: {
    backgroundColor: 'rgba(31, 42, 68, 0.04)',
    borderColor: GinitTheme.colors.border,
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  placeSuggestRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 2,
    paddingRight: 4,
    marginBottom: 10,
  },
  placeSuggestChip: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 999,
    backgroundColor: 'rgba(31, 42, 68, 0.04)',
    borderWidth: 1,
    borderColor: GinitTheme.colors.border,
  },
  placeSuggestChipPressed: {
    opacity: 0.9,
    backgroundColor: 'rgba(31, 42, 68, 0.10)',
    borderColor: 'rgba(31, 42, 68, 0.45)',
  },
  placeSuggestChipText: {
    fontSize: 12,
    fontWeight: '600',
    color: GinitTheme.colors.text,
    maxWidth: 220,
  },
  scheduleCalendarWrap: {
    marginTop: 10,
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: GinitTheme.colors.border,
    backgroundColor: 'rgba(255, 255, 255, 0.45)',
    overflow: 'hidden',
  },
  scheduleCalendarHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: GinitTheme.colors.border,
  },
  scheduleCalendarTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: GinitTheme.colors.text,
    letterSpacing: -0.2,
  },
  scheduleCalendarTitlePress: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 34,
  },
  scheduleCalendarCarouselHost: {
    width: '100%',
    height: 274,
  },
  scheduleCalendarPagerScroll: {
    flex: 1,
    minHeight: 0,
  },
  scheduleCalendarPagerContent: {
    paddingVertical: 10,
    paddingHorizontal: 0,
  },
  calendarNavBtn: {
    width: 34,
    height: 34,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(31, 42, 68, 0.04)',
    borderWidth: 1,
    borderColor: GinitTheme.colors.border,
  },
  calendarNavBtnPressed: {
    opacity: 0.9,
  },
  calendarDowRow: {
    flexDirection: 'row',
    paddingHorizontal: 8,
    paddingTop: 8,
    paddingBottom: 6,
  },
  calendarDowText: {
    flex: 1,
    textAlign: 'center',
    fontSize: 11,
    fontWeight: '600',
    color: GinitTheme.colors.textMuted,
  },
  calendarGrid: {
    paddingHorizontal: 8,
    paddingBottom: 10,
  },
  calendarWeekRow: {
    flexDirection: 'row',
    width: '100%',
    marginBottom: 8,
  },
  calendarWeekRowEmpty: {
    marginBottom: 2,
  },
  calendarCell: {
    flexGrow: 1,
    flexBasis: 0,
    paddingHorizontal: 4,
    paddingVertical: 6,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 44,
    borderRadius: 12,
  },
  calendarCellCompact: {
    paddingVertical: 3,
    minHeight: 22,
  },
  calendarCellRowEmpty: {
    paddingVertical: 2,
    minHeight: 18,
  },
  calendarCellOut: {
    opacity: 0.42,
  },
  calendarCellHas: {
    backgroundColor: 'rgba(31, 42, 68, 0.10)',
    borderWidth: 1,
    borderColor: 'rgba(31, 42, 68, 0.45)',
  },
  calendarCellAgentDemo: {
    backgroundColor: `${GinitTheme.colors.primary}22`,
  },
  calendarCellPressed: {
    opacity: 0.9,
  },
  calendarCellDisabled: {
    opacity: 0.35,
  },
  calendarCellDay: {
    fontSize: 13,
    fontWeight: '600',
    color: GinitTheme.colors.text,
    lineHeight: 18,
  },
  calendarCellDayCompact: {
    fontSize: 12,
    lineHeight: 16,
  },
  calendarCellDayOut: {
    color: GinitTheme.colors.textMuted,
  },
  calendarTimesWrap: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarCellMeta: {
    marginTop: 2,
    fontSize: 10,
    fontWeight: '600',
    color: GinitTheme.colors.primary,
  },
  calendarCellMetaCompact: {
    marginTop: 1,
    fontSize: 9,
  },
  calendarCellMetaEmpty: {
    marginTop: 2,
    fontSize: 10,
    color: 'transparent',
  },
  calendarCellMetaEmptyCompact: {
    marginTop: 1,
    fontSize: 9,
  },
  timePickHint: {
    fontSize: 12,
    fontWeight: '600',
    color: GinitTheme.colors.textMuted,
  },
  placeResultsScrollHost: {
    width: '100%',
    marginTop: 4,
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: GinitTheme.colors.border,
    backgroundColor: 'rgba(255, 255, 255, 0.45)',
    overflow: 'hidden',
  },
  placeResultsScrollView: {
    flex: 1,
  },
  placeResultsScrollContent: {
    paddingBottom: 10,
    paddingHorizontal: 4,
  },
  /** 제목·주소 각 2줄 + 카카오·네이버 버튼까지 포함(이미지 112 + 여백) — `overflow: hidden` 호스트에 맞춤 */
  placeResultsCarouselHost: {
    height: 274,
  },
  placeResultsCarouselContent: {
    paddingVertical: 10,
    paddingHorizontal: 10,
    gap: 10,
  },
  placeResultsLoadingMore: {
    width: 76,
    height: 274,
    alignItems: 'center',
    justifyContent: 'center',
  },
  placeResultsGrid: {
    flexDirection: 'column',
    gap: 10,
  },
  placeResultsStatus: {
    width: '100%',
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  placeResultsStatusText: {
    fontSize: 13,
    fontWeight: '700',
    color: GinitTheme.colors.textMuted,
    textAlign: 'center',
  },
  placeResultCard: {
    width: '100%',
    borderRadius: 14,
    backgroundColor: GinitTheme.fixedGlassCard.fill,
    borderWidth: 1,
    borderColor: GinitTheme.colors.border,
    paddingVertical: 10,
    paddingHorizontal: 10,
  },
  placeResultImageCard: {
    width: 176,
    paddingVertical: 10,
    paddingHorizontal: 10,
  },
  /** 가로 캐러셀(`placeResultsCarouselHost` 274) − 세로 패딩 20 기준 — 카카오·네이버 버튼을 카드 하단에 고정 */
  placeResultProposalCardWrap: {
    minHeight: 254,
    flexDirection: 'column',
  },
  placeResultProposalPressFill: {
    flex: 1,
    minHeight: 0,
  },
  placeResultProposalPressInner: {
    flexGrow: 1,
  },
  placeResultImageCardSelected: {
    borderColor: GinitTheme.colors.primary,
    backgroundColor: 'rgba(255, 255, 255, 0.82)',
  },
  placeResultImageWrap: {
    width: '100%',
    height: 112,
    borderRadius: 12,
    overflow: 'hidden',
    marginBottom: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.55)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(15, 23, 42, 0.12)',
  },
  placeResultImage: {
    width: '100%',
    height: '100%',
  },
  placeResultImageFallback: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.06)',
  },
  placeResultImageOverlay: {
    position: 'absolute',
    top: 8,
    right: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.82)',
    borderRadius: 999,
    padding: 4,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(15, 23, 42, 0.12)',
  },
  placeResultCardPressed: {
    opacity: 0.92,
    transform: [{ scale: 0.99 }],
  },
  placeResultTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: GinitTheme.colors.text,
    lineHeight: 18,
    marginBottom: 6,
  },
  placeResultAddr: {
    fontSize: 11,
    fontWeight: '700',
    color: GinitTheme.colors.textMuted,
    lineHeight: 15,
  },
  placePickedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    marginTop: 8,
    alignSelf: 'stretch',
  },
  placePickedName: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    fontWeight: '600',
    color: GinitTheme.colors.text,
  },
  placePickedRemove: {
    fontSize: 12,
    fontWeight: '600',
    color: GinitTheme.colors.danger,
  },
  /** + 후보 추가 — 스펙 */
  addCandidateBtn: {
    alignSelf: 'stretch',
    marginBottom: 8,
    backgroundColor: 'rgba(31, 42, 68, 0.04)',
    borderWidth: 1,
    borderColor: GinitTheme.colors.border,
    borderRadius: 16,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addCandidateBtnLabel: {
    color: GinitTheme.colors.primary,
    fontSize: 15,
    fontWeight: '600',
    textAlign: 'center',
  },
  addCandidateBtnPressed: {
    opacity: 0.95,
    backgroundColor: 'rgba(31, 42, 68, 0.10)',
    borderColor: 'rgba(31, 42, 68, 0.45)',
  },
  wizardFieldLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: GinitTheme.colors.textSub,
    marginBottom: 8,
    marginTop: 8,
    marginLeft: 8,
  },
});
