import { StyleSheet } from 'react-native';

const TRUST_BLUE = '#0052CC';
const ENERGETIC_ORANGE = '#FF8A00';
const INPUT_PLACEHOLDER = 'rgba(255, 255, 255, 0.4)';

export const wizardSpecialtyStyles = StyleSheet.create({
  fieldLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: 'rgba(248, 250, 252, 0.75)',
    marginBottom: 8,
  },
  fieldHint: {
    fontSize: 12,
    fontWeight: '600',
    color: 'rgba(248, 250, 252, 0.5)',
    marginBottom: 10,
  },
  textInput: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.14)',
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    fontWeight: '600',
    color: '#F8FAFC',
  },
  resultsBox: {
    marginTop: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    backgroundColor: 'rgba(15, 23, 42, 0.35)',
    overflow: 'hidden',
  },
  resultRow: {
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: 'rgba(255, 255, 255, 0.08)',
  },
  resultTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: 'rgba(248, 250, 252, 0.95)',
  },
  resultMeta: {
    marginTop: 4,
    fontSize: 12,
    fontWeight: '600',
    color: 'rgba(147, 197, 253, 0.85)',
  },
  pickedBlock: {
    marginTop: 14,
    padding: 14,
    borderRadius: 14,
    backgroundColor: 'rgba(0, 82, 204, 0.18)',
    borderWidth: 1,
    borderColor: 'rgba(0, 82, 204, 0.45)',
  },
  pickedTitle: {
    fontSize: 16,
    fontWeight: '900',
    color: '#F8FAFC',
  },
  pickedSub: {
    marginTop: 6,
    fontSize: 13,
    fontWeight: '600',
    color: 'rgba(248, 250, 252, 0.72)',
    lineHeight: 19,
  },
  clearLink: {
    marginTop: 10,
    alignSelf: 'flex-start',
  },
  clearLinkText: {
    fontSize: 13,
    fontWeight: '800',
    color: 'rgba(147, 197, 253, 0.95)',
  },
  chipWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 4,
  },
  glassChip: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 999,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.14)',
  },
  glassChipOn: {
    backgroundColor: 'rgba(0, 82, 204, 0.28)',
    borderColor: 'rgba(147, 197, 253, 0.55)',
    shadowColor: TRUST_BLUE,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 4,
  },
  glassChipPressed: {
    opacity: 0.88,
  },
  glassChipText: {
    fontSize: 13,
    fontWeight: '800',
    color: 'rgba(248, 250, 252, 0.92)',
  },
  segmentRow: {
    flexDirection: 'row',
    borderRadius: 14,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    marginTop: 4,
  },
  segmentThird: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 6,
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
  },
  segmentThirdOn: {
    backgroundColor: 'rgba(0, 82, 204, 0.35)',
  },
  segmentTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: 'rgba(248, 250, 252, 0.55)',
    textAlign: 'center',
  },
  segmentTitleOn: {
    color: '#F8FAFC',
  },
  segmentSub: {
    marginTop: 2,
    fontSize: 10,
    fontWeight: '600',
    color: 'rgba(248, 250, 252, 0.45)',
    textAlign: 'center',
  },
  /** MovieSearch — 큰 그리드 카드 셸 */
  movieHeroShell: {
    marginTop: 4,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    backgroundColor: 'rgba(15, 23, 42, 0.35)',
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 8,
    flexDirection: 'column',
  },
  movieListScroll: {
    flex: 1,
    minHeight: 0,
  },
  movieListStack: {
    gap: 12,
    paddingBottom: 12,
    paddingTop: 6,
  },
  /** Blur 없는 환경(web 등)용 글래스 대체 */
  movieListRowCardFallback: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    backgroundColor: 'rgba(15, 23, 42, 0.62)',
    overflow: 'hidden',
    shadowColor: '#020617',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.55,
    shadowRadius: 22,
    elevation: 10,
  },
  movieListRowOuter: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.14)',
    overflow: 'hidden',
    position: 'relative',
    shadowColor: '#020617',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.55,
    shadowRadius: 22,
    elevation: 10,
  },
  movieListRowInner: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 14,
    paddingVertical: 12,
    paddingHorizontal: 12,
    zIndex: 1,
  },
  movieListPosterWrap: {
    width: 92,
    alignSelf: 'flex-start',
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: 'rgba(0, 0, 0, 0.28)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  movieListPosterImg: {
    width: 92,
    aspectRatio: 2 / 3,
    position: 'relative' as const,
  },
  moviePosterSkeleton: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15, 23, 42, 0.55)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
  },
  moviePosterImgFill: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
    zIndex: 1,
  },
  movieListRowPressedOrange: {
    borderColor: 'rgba(255, 138, 0, 0.75)',
    backgroundColor: 'rgba(255, 138, 0, 0.1)',
    shadowColor: ENERGETIC_ORANGE,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 14,
    elevation: 10,
  },
  movieRankBadge: {
    position: 'absolute',
    top: 6,
    left: 6,
    zIndex: 3,
    minWidth: 26,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    backgroundColor: TRUST_BLUE,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.22)',
  },
  movieRankBadgeText: {
    fontSize: 13,
    fontWeight: '900',
    color: '#FFFFFF',
  },
  movieRightCol: {
    flex: 1,
    minWidth: 0,
    justifyContent: 'center',
    gap: 8,
  },
  movieTitleGlass: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
  },
  movieYearUnderTitle: {
    marginTop: 5,
    fontSize: 12,
    fontWeight: '700',
    color: 'rgba(147, 197, 253, 0.88)',
  },
  /** Pretendard Bold 스펙 — `PretendardBold` 폰트 로드 시 fontFamily 적용 */
  movieListTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: '#F8FAFC',
    letterSpacing: -0.35,
    lineHeight: 23,
  },
  movieRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  movieStarIcon: {
    fontSize: 15,
    color: ENERGETIC_ORANGE,
    fontWeight: '900',
    marginTop: -1,
  },
  movieRatingNumber: {
    fontSize: 14,
    fontWeight: '900',
    color: ENERGETIC_ORANGE,
    letterSpacing: -0.2,
  },
  movieSynopsis: {
    fontSize: 13,
    fontWeight: '600',
    color: 'rgba(248, 250, 252, 0.68)',
    lineHeight: 19,
  },
  movieRatingBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    backgroundColor: 'rgba(0, 82, 204, 0.28)',
    borderWidth: 1,
    borderColor: 'rgba(147, 197, 253, 0.55)',
    shadowColor: TRUST_BLUE,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.35,
    shadowRadius: 8,
    elevation: 3,
  },
  movieRatingBadgeText: {
    fontSize: 11,
    fontWeight: '900',
    color: 'rgba(248, 250, 252, 0.95)',
  },
  moviePosterImg: {
    width: '100%',
    height: '100%',
  },
  movieCompactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 8,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(0, 82, 204, 0.45)',
    backgroundColor: 'rgba(0, 82, 204, 0.18)',
    shadowColor: TRUST_BLUE,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 4,
  },
  movieCompactPoster: {
    width: 44,
    height: 66,
    borderRadius: 10,
    overflow: 'hidden',
    backgroundColor: 'rgba(0, 0, 0, 0.25)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
  },
  movieCompactTextCol: {
    flex: 1,
    minWidth: 0,
  },
  movieCompactTitle: {
    fontSize: 15,
    fontWeight: '900',
    color: '#F8FAFC',
  },
  movieCompactMeta: {
    marginTop: 2,
    fontSize: 12,
    fontWeight: '600',
    color: 'rgba(147, 197, 253, 0.85)',
  },
  movieCompactBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: 'rgba(0, 82, 204, 0.35)',
    borderWidth: 1,
    borderColor: 'rgba(147, 197, 253, 0.5)',
  },
  movieCompactBadgeText: {
    fontSize: 11,
    fontWeight: '900',
    color: 'rgba(248, 250, 252, 0.95)',
  },
});

export { INPUT_PLACEHOLDER };
