import { Platform, StyleSheet, type ViewStyle } from 'react-native';

import { GinitTheme } from '@/constants/ginit-theme';

const TRUST_BLUE = GinitTheme.colors.primary;
/** 영화 리스트 포스터 고정 너비 (80~100px 명세 중간값) */
export const MOVIE_LIST_POSTER_WIDTH = 92;
const ENERGETIC_ORANGE = GinitTheme.colors.warning;
const INPUT_PLACEHOLDER = GinitTheme.glassModal.placeholder;

export const wizardSpecialtyStyles = StyleSheet.create({
  fieldLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: GinitTheme.colors.textSub,
    marginBottom: 8,
  },
  fieldHint: {
    fontSize: 12,
    fontWeight: '600',
    color: GinitTheme.colors.textMuted,
    marginBottom: 10,
  },
  textInput: {
    backgroundColor: GinitTheme.glassModal.inputFill,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: GinitTheme.colors.border,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    fontWeight: '600',
    color: GinitTheme.colors.text,
  },
  resultsBox: {
    marginTop: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: GinitTheme.colors.border,
    backgroundColor: 'rgba(255, 255, 255, 0.72)',
    overflow: 'hidden',
  },
  resultRow: {
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: 'rgba(255, 255, 255, 0.08)',
  },
  resultTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: GinitTheme.colors.text,
  },
  resultMeta: {
    marginTop: 4,
    fontSize: 12,
    fontWeight: '600',
    color: GinitTheme.colors.textMuted,
  },
  pickedBlock: {
    marginTop: 14,
    padding: 14,
    borderRadius: 14,
    backgroundColor: GinitTheme.colors.primarySoft,
    borderWidth: 1,
    borderColor: GinitTheme.colors.border,
  },
  pickedTitle: {
    fontSize: 16,
    fontWeight: '900',
    color: GinitTheme.colors.text,
  },
  pickedSub: {
    marginTop: 6,
    fontSize: 13,
    fontWeight: '600',
    color: GinitTheme.colors.textMuted,
    lineHeight: 19,
  },
  clearLink: {
    marginTop: 10,
    alignSelf: 'flex-start',
  },
  clearLinkText: {
    fontSize: 13,
    fontWeight: '800',
    color: GinitTheme.colors.primary,
  },
  chipWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 4,
  },
  glassChip: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 999,
    backgroundColor: 'rgba(255, 255, 255, 0.72)',
    borderWidth: 1,
    borderColor: GinitTheme.colors.border,
  },
  glassChipOn: {
    backgroundColor: GinitTheme.colors.primarySoft,
    borderColor: 'rgba(31, 42, 68, 0.40)',
    shadowColor: 'rgba(31, 42, 68, 0.22)',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 4,
  },
  glassChipPressed: {
    opacity: 0.88,
  },
  glassChipText: {
    fontSize: 13,
    fontWeight: '800',
    color: GinitTheme.colors.text,
  },
  segmentRow: {
    flexDirection: 'row',
    borderRadius: 14,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: GinitTheme.colors.border,
    marginTop: 4,
  },
  segmentThird: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 6,
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.55)',
  },
  segmentThirdOn: {
    backgroundColor: 'rgba(31, 42, 68, 0.10)',
  },
  segmentTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: GinitTheme.colors.textSub,
    textAlign: 'center',
  },
  segmentTitleOn: {
    color: GinitTheme.colors.primary,
  },
  segmentSub: {
    marginTop: 2,
    fontSize: 10,
    fontWeight: '600',
    color: GinitTheme.colors.textMuted,
    textAlign: 'center',
  },
  /** MovieSearch — 큰 그리드 카드 셸 */
  movieHeroShell: {
    marginTop: 4,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: GinitTheme.colors.border,
    backgroundColor: 'rgba(255, 255, 255, 0.72)',
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 8,
    flexDirection: 'column',
  },
  movieListScroll: {
    flex: 1,
    minHeight: 0,
  },
  movieListStack: {
    gap: 12,
    paddingBottom: 12,
    paddingTop: 6,
  },
  movieListItemOuter: {
    width: Platform.OS === 'web' ? ('100%' as const) : undefined,
    alignSelf: 'stretch',
  },
  /** Blur 없는 환경(web 등)용 글래스 대체 */
  movieListRowCardFallback: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: GinitTheme.colors.border,
    backgroundColor: 'rgba(255, 255, 255, 0.86)',
    overflow: 'hidden',
  },
  movieListRowWrap: {
    borderRadius: 16,
    backgroundColor: Platform.OS === 'android' ? '#FFFFFF' : 'transparent',
    shadowColor: 'rgba(15, 23, 42, 0.14)',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 1,
    shadowRadius: 22,
    elevation: 10,
  },
  movieListRowOuter: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: GinitTheme.colors.border,
    overflow: 'hidden',
    position: 'relative',
  },
  movieListRowInner: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'nowrap' as const,
    alignItems: 'flex-start',
    width: '100%',
    gap: 16,
    paddingVertical: 12,
    paddingHorizontal: 12,
    zIndex: 1,
  },
  movieListPosterWrap: {
    width: MOVIE_LIST_POSTER_WIDTH,
    flexShrink: 0,
    alignSelf: 'flex-start',
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: 'rgba(255, 255, 255, 0.72)',
    borderWidth: 1,
    borderColor: GinitTheme.colors.border,
  },
  movieListPosterImg: {
    width: MOVIE_LIST_POSTER_WIDTH,
    aspectRatio: 2 / 3,
    flexShrink: 0,
    position: 'relative' as const,
  },
  moviePosterSkeleton: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: GinitTheme.colors.bgAlt,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
  },
  moviePosterImgFill: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
    zIndex: 1,
  },
  movieListRowPressedOrange: {
    borderColor: 'rgba(255, 138, 0, 0.75)',
    backgroundColor: 'rgba(255, 138, 0, 0.1)',
  },
  movieRankBadge: {
    position: 'absolute',
    top: 6,
    left: 6,
    zIndex: 3,
    minWidth: 26,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    backgroundColor: TRUST_BLUE,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.22)',
  },
  movieRankBadgeText: {
    fontSize: 13,
    fontWeight: '900',
    color: '#FFFFFF',
  },
  movieRightCol: {
    flex: 1,
    flexShrink: 1,
    minWidth: 0,
    flexDirection: 'column',
    justifyContent: 'flex-start',
    gap: 8,
  },
  movieTitleGlass: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.72)',
    borderWidth: 1,
    borderColor: GinitTheme.colors.border,
  },
  movieYearUnderTitle: {
    marginTop: 5,
    fontSize: 12,
    fontWeight: '700',
    color: GinitTheme.colors.textMuted,
  },
  /** Pretendard Bold 스펙 — `PretendardBold` 폰트 로드 시 fontFamily 적용 */
  movieListTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: GinitTheme.colors.text,
    letterSpacing: -0.35,
    lineHeight: 23,
  },
  movieRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  movieStarIcon: {
    fontSize: 15,
    color: ENERGETIC_ORANGE,
    fontWeight: '900',
    marginTop: -1,
  },
  movieRatingNumber: {
    fontSize: 14,
    fontWeight: '900',
    color: ENERGETIC_ORANGE,
    letterSpacing: -0.2,
  },
  movieSynopsis: {
    fontSize: 13,
    fontWeight: '600',
    color: GinitTheme.colors.textMuted,
    lineHeight: 19,
  },
  movieRatingBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    backgroundColor: 'rgba(0, 82, 204, 0.28)',
    borderWidth: 1,
    borderColor: 'rgba(147, 197, 253, 0.55)',
  },
  movieRatingBadgeText: {
    fontSize: 11,
    fontWeight: '900',
    color: GinitTheme.colors.text,
  },
  moviePosterImg: {
    width: '100%',
    height: '100%',
  },
  movieCompactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 8,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(0, 82, 204, 0.45)',
    backgroundColor: 'rgba(0, 82, 204, 0.18)',
  },
  movieCompactPoster: {
    width: 44,
    height: 66,
    borderRadius: 10,
    overflow: 'hidden',
    backgroundColor: 'rgba(0, 0, 0, 0.25)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
  },
  movieCompactTextCol: {
    flex: 1,
    minWidth: 0,
  },
  movieCompactTitle: {
    fontSize: 15,
    fontWeight: '900',
    color: GinitTheme.colors.text,
  },
  movieCompactMeta: {
    marginTop: 2,
    fontSize: 12,
    fontWeight: '600',
    color: GinitTheme.colors.textMuted,
  },
  movieCompactBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: 'rgba(0, 82, 204, 0.35)',
    borderWidth: 1,
    borderColor: 'rgba(147, 197, 253, 0.5)',
  },
  movieCompactBadgeText: {
    fontSize: 11,
    fontWeight: '900',
    color: GinitTheme.colors.text,
  },
  /** 다중 후보: 세로 스택(웹 포함 전체 너비) */
  movieCandidatesColumn: {
    flexDirection: 'column',
    gap: 12,
    width: Platform.OS === 'web' ? ('100%' as const) : undefined,
    alignSelf: 'stretch',
  },
  movieConfirmedCard: {
    position: 'relative',
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 16,
    paddingVertical: 12,
    paddingHorizontal: 12,
    paddingRight: 40,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(0, 82, 204, 0.55)',
    backgroundColor: 'rgba(0, 82, 204, 0.16)',
    overflow: 'hidden',
  },
  movieConfirmedRemoveHit: {
    position: 'absolute',
    top: 6,
    right: 6,
    zIndex: 6,
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.92)',
    borderWidth: 1,
    borderColor: GinitTheme.colors.border,
  },
  movieAddOutlineBtn: {
    marginTop: 4,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: TRUST_BLUE,
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  movieAddOutlineBtnPressed: {
    opacity: 0.88,
    backgroundColor: 'rgba(0, 82, 204, 0.12)',
  },
  movieAddOutlineBtnLabel: {
    fontSize: 15,
    fontWeight: '800',
    color: GinitTheme.colors.primary,
  },
  /** MovieSearch — 장소 후보(`VoteCandidatesForm` placesInner)와 동일 레이아웃 톤 */
  movieWizardAiBorder: {
    borderRadius: 16,
    padding: 2,
    marginBottom: 8,
  },
  movieWizardAiInner: {
    borderRadius: 14,
    backgroundColor: GinitTheme.colors.surface,
    borderWidth: 1,
    borderColor: GinitTheme.colors.border,
    paddingHorizontal: 12,
    paddingVertical: 10,
    minHeight: 0,
  },
  movieWizardAiInput: {
    minHeight: 0,
    fontSize: 16,
    fontWeight: '700',
    color: GinitTheme.colors.text,
    lineHeight: 22,
    padding: 0,
    margin: 0,
    flex: 1,
  },
  movieResultsScrollHost: {
    width: '100%',
    marginTop: 4,
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: GinitTheme.colors.border,
    backgroundColor: 'rgba(255, 255, 255, 0.45)',
    overflow: 'hidden',
  },
  movieResultsCarouselHost: {
    height: 274,
  },
  movieResultsScrollContent: {
    paddingVertical: 10,
    paddingHorizontal: 10,
    gap: 10,
  },
  movieResultsStatus: {
    width: '100%',
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  movieResultsStatusText: {
    fontSize: 13,
    fontWeight: '700',
    color: GinitTheme.colors.textMuted,
    textAlign: 'center',
  },
  movieResultImageCard: {
    width: 176,
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderRadius: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.72)',
    borderWidth: 1,
    borderColor: GinitTheme.colors.border,
  },
  movieResultImageCardSelected: {
    borderColor: 'rgba(134, 211, 183, 0.9)',
    backgroundColor: 'rgba(255, 255, 255, 0.82)',
  },
  movieResultProposalCardWrap: {
    minHeight: 254,
    flexDirection: 'column',
  },
  movieResultProposalPressFill: {
    flex: 1,
    minHeight: 0,
  },
  movieResultProposalPressInner: {
    flexGrow: 1,
  },
  movieResultImageWrap: {
    width: '100%',
    height: 112,
    borderRadius: 12,
    overflow: 'hidden',
    marginBottom: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.55)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(15, 23, 42, 0.12)',
  },
  movieResultImageOverlay: {
    position: 'absolute',
    top: 8,
    right: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.82)',
    borderRadius: 999,
    padding: 4,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(15, 23, 42, 0.12)',
  },
  movieResultCardPressed: {
    opacity: 0.92,
    transform: [{ scale: 0.99 }],
  },
  movieResultTitle: {
    fontSize: 13,
    fontWeight: '900',
    color: GinitTheme.colors.text,
    lineHeight: 18,
    marginBottom: 6,
  },
  movieResultMeta: {
    fontSize: 11,
    fontWeight: '700',
    color: GinitTheme.colors.textMuted,
    lineHeight: 15,
  },
  /** 장소 후보 `placeResultDetailBtn`과 동일 스펙 */
  movieResultDetailBtn: {
    marginTop: 8,
    flexShrink: 0,
    alignSelf: 'stretch',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    borderRadius: GinitTheme.radius.button,
    borderWidth: 1,
    borderColor: GinitTheme.colors.primary,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
  },
  movieResultDetailBtnText: {
    fontSize: 12,
    fontWeight: '900',
    color: GinitTheme.colors.primary,
  },
});

/**
 * 웹 전용: `backdrop-filter` + 반투명 면 + 얇은 테두리 (react-native-web DOM)
 */
export const movieListRowWebGlassStyle: ViewStyle =
  Platform.OS === 'web'
    ? ({
        backdropFilter: 'blur(12px)',
        WebkitBackdropFilter: 'blur(12px)',
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.2)',
        borderStyle: 'solid',
      } as ViewStyle)
    : ({} as ViewStyle);

/** 웹: 후보 추가 버튼에 얇은 글래스 느낌 */
export const movieAddOutlineBtnWebStyle: ViewStyle =
  Platform.OS === 'web'
    ? ({
        backdropFilter: 'blur(10px)',
        WebkitBackdropFilter: 'blur(10px)',
        backgroundColor: 'rgba(255, 255, 255, 0.06)',
      } as ViewStyle)
    : ({} as ViewStyle);

export { INPUT_PLACEHOLDER };
